name: Talk Proposal
description: Submit your Talk Proposal
title: "Talk Proposal: #{your title here}"
labels: [Talk]
body:
  - type: input
    attributes:
      label: Full name
      placeholder: "your name"

  - type: input
    attributes:
      label: GitHub profile
      placeholder: "https://github.com/<your_github_username>"
      
  - type: input
    attributes:
      label: Social link
      placeholder: "your social media link"

  - type: input
    attributes:
      label: "Proposal type"
      placeholder: "Talk or Lightning Talk"

  - type: input
    attributes:
      label: "Title"
      placeholder: "Your talk title here"
      
  - type: textarea
    attributes:
      label: Description
      placeholder: "Your talk description here"

  - type: dropdown
    attributes:
      label: Preferred Meetup you would like to present in
      options: 
        - "Any"
        - "Next"
        - "January/February"
        - "March/April"
        - "May/June"
        - "July/August"
        - "September/October"
        - "November/December"
